# Generated by Django 6.0.2 on 2026-03-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
