# Generated by Django 6.0.2 on 2026-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(default='developer', max_length=100),
            preserve_default=False,
        ),
    ]
