# Generated by Django 6.0.2 on 2026-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobapplication_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
