# Generated by Django 6.0.2 on 2026-07-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Wishlist', 'Wishlist'), ('Applied', 'Applied'), ('Interview', 'Interview'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Wishlist'),
        ),
    ]
