# Generated by Django 6.0.2 on 2026-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_job_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
